import type { ModelEndpoint, ModelProvider } from "@/types";

// CLI model lists below are derived from real CLI output:
//   - claude-code:  `claude --model <invalid>` error + aliases (opus/sonnet/haiku)
//   - codex:        `codex debug models`
//   - copilot-cli:  `copilot help config` model section (authoritative)
//   - gemini-cli:   official model catalog
// `dynamicModels: true` lets `/api/model-providers/[id]/models` refresh at runtime.

export const modelEndpoints: ModelEndpoint[] = [
  {
    id: "claude-code",
    provider: "claude-code",
    model: "claude-sonnet-4-6",
    models: [
      "claude-opus-4-7",
      "claude-opus-4-1",
      "claude-sonnet-4-6",
      "claude-sonnet-4-5",
      "claude-haiku-4-5",
      "opus",
      "sonnet",
      "haiku",
    ],
    mode: "cli",
    enabled: true,
    dynamicModels: true,
    reasoningEfforts: ["low", "medium", "high", "xhigh"],
  },
  {
    id: "codex",
    provider: "codex",
    model: "gpt-5.2",
    models: [
      "gpt-5.5",
      "gpt-5.5-codex",
      "gpt-5.5-mini",
      "gpt-5.4",
      "gpt-5.4-mini",
      "gpt-5.3-codex",
      "gpt-5.2",
      "gpt-5.2-codex",
      "gpt-5.2-mini",
      "gpt-4.1",
      "o4-mini",
      "o3",
    ],
    mode: "cli",
    enabled: true,
    dynamicModels: true,
    reasoningEfforts: ["low", "medium", "high", "xhigh"],
  },
  {
    id: "copilot-cli",
    provider: "copilot-cli",
    model: "claude-sonnet-4.6",
    models: [
      "claude-sonnet-4.6",
      "claude-sonnet-4.5",
      "claude-haiku-4.5",
      "claude-opus-4.7",
      "claude-opus-4.6",
      "claude-opus-4.6-fast",
      "claude-opus-4.5",
      "gpt-5.5",
      "gpt-5.4",
      "gpt-5.3-codex",
      "gpt-5.2-codex",
      "gpt-5.2",
      "gpt-5.4-mini",
      "gpt-5-mini",
      "gpt-4.1",
    ],
    mode: "cli",
    enabled: true,
    dynamicModels: true,
    reasoningEfforts: ["low", "medium", "high", "xhigh"],
  },
  {
    id: "ollama",
    provider: "ollama",
    model: "llama3.2:latest",
    models: [
      "llama3.2:latest",
      "gpt-oss:120b-cloud",
      "gpt-oss:20b-cloud",
      "deepseek-v3.1:671b-cloud",
      "qwen3-coder:480b-cloud",
      "qwen3-vl:235b-cloud",
      "minimax-m2:cloud",
      "glm-4.6:cloud",
    ],
    baseUrl: "http://127.0.0.1:11434",
    mode: "local",
    enabled: true,
    dynamicModels: true,
    thinkingLevels: ["off", "think", "think-hard"],
  },
  {
    id: "nvidia",
    provider: "nvidia",
    model: "nvidia/llama-3.3-nemotron-super-49b-v1",
    baseUrl: "https://integrate.api.nvidia.com/v1",
    mode: "cloud",
    enabled: false,
    dynamicModels: true,
    requiresApiKey: true,
    reasoningEfforts: ["minimal", "low", "medium", "high"],
  },
  {
    id: "anthropic",
    provider: "anthropic",
    model: "claude-opus-4-7",
    models: [
      "claude-opus-4-7",
      "claude-sonnet-4-6",
      "claude-haiku-4-5-20251001",
      "claude-sonnet-4-5",
      "claude-opus-4-1",
    ],
    mode: "cloud",
    enabled: false,
    requiresApiKey: true,
    dynamicModels: true,
    thinkingLevels: ["off", "think", "think-hard", "think-harder"],
  },
  {
    id: "openai",
    provider: "openai",
    model: "gpt-5.2",
    models: [
      "gpt-5.5",
      "gpt-5.5-mini",
      "gpt-5.5-nano",
      "gpt-5.5-thinking",
      "gpt-5.2",
      "gpt-5.2-mini",
      "gpt-5.2-nano",
      "gpt-4.1",
      "o4-mini",
      "o3",
    ],
    mode: "cloud",
    enabled: false,
    requiresApiKey: true,
    dynamicModels: true,
    reasoningEfforts: ["minimal", "low", "medium", "high"],
  },
  {
    id: "openrouter",
    provider: "openrouter",
    model: "auto",
    // Curated short-list — full catalog is fetched dynamically. `auto` lets
    // OpenRouter pick the best model for the prompt.
    models: [
      "auto",
      "anthropic/claude-opus-4-7",
      "anthropic/claude-sonnet-4-6",
      "anthropic/claude-haiku-4-5",
      "openai/gpt-5.5",
      "openai/gpt-5.5-mini",
      "openai/o4-mini",
      "google/gemini-2.5-pro",
      "google/gemini-2.5-flash",
      "meta-llama/llama-3.3-70b-instruct",
      "deepseek/deepseek-v3",
      "qwen/qwen-2.5-coder-32b",
    ],
    mode: "cloud",
    enabled: false,
    requiresApiKey: true,
    dynamicModels: true,
    reasoningEfforts: ["minimal", "low", "medium", "high"],
  },
  {
    id: "gemini-cli",
    provider: "gemini-cli",
    model: "gemini-2.5-pro",
    models: [
      "gemini-3-pro-preview",
      "gemini-2.5-pro",
      "gemini-2.5-flash",
      "gemini-2.5-flash-lite",
      "gemini-2.0-flash",
    ],
    mode: "cli",
    enabled: true,
    dynamicModels: true,
    thinkingLevels: ["off", "think", "think-hard"],
  },
  {
    id: "gemini",
    provider: "gemini",
    model: "gemini-2.5-pro",
    models: [
      "gemini-3-pro-preview",
      "gemini-2.5-pro",
      "gemini-2.5-flash",
      "gemini-2.5-flash-lite",
      "gemini-2.0-flash",
    ],
    mode: "cloud",
    enabled: false,
    requiresApiKey: true,
    dynamicModels: true,
    thinkingLevels: ["off", "think", "think-hard"],
  },
  { id: "grok", provider: "grok", model: "grok-4", models: ["grok-4", "grok-4-fast", "grok-3", "grok-3-mini"], mode: "cloud", enabled: false, requiresApiKey: true, dynamicModels: true, reasoningEfforts: ["minimal", "low", "medium", "high"] },
  { id: "custom", provider: "custom", model: "custom-endpoint", mode: "cloud", enabled: false },
];

export function listModelProviders() {
  return modelEndpoints;
}

export function getProvider(id: ModelProvider | string) {
  return modelEndpoints.find((endpoint) => endpoint.id === id || endpoint.provider === id);
}
