import type { ModelEndpoint, ModelProvider } from "@/types";

export const modelEndpoints: ModelEndpoint[] = [
  {
    id: "claude-code",
    provider: "claude-code",
    model: "claude-opus-4-7",
    models: [
      "claude-opus-4-7",
      "claude-sonnet-4-6",
      "claude-haiku-4-5",
      "claude-sonnet-4-5",
      "claude-opus-4-1",
    ],
    mode: "cli",
    enabled: true,
    dynamicModels: true,
  },
  {
    id: "codex",
    provider: "codex",
    model: "gpt-5.5",
    models: [
      "gpt-5.5",
      "gpt-5.5-mini",
      "gpt-5.5-thinking",
      "gpt-5.2",
      "gpt-5.2-mini",
      "gpt-4.1",
      "o4-mini",
      "o3",
    ],
    mode: "cli",
    enabled: true,
    dynamicModels: true,
  },
  {
    id: "copilot-cli",
    provider: "copilot-cli",
    model: "gpt-5.5",
    models: [
      "claude-sonnet-4.6",
      "claude-sonnet-4.5",
      "claude-haiku-4.5",
      "claude-opus-4.7",
      "claude-opus-4.6",
      "claude-opus-4.6-fast",
      "claude-opus-4.5",
      "claude-sonnet-4",
      "gpt-5.5",
      "gpt-5.4",
      "gpt-5.3-codex",
      "gpt-5.2-codex",
      "gpt-5.2",
      "gpt-5.1",
      "gpt-5.4-mini",
      "gpt-5-mini",
      "gpt-4.1",
    ],
    mode: "cli",
    enabled: true,
    dynamicModels: true,
  },
  {
    id: "ollama",
    provider: "ollama",
    model: "llama3.2:latest",
    models: [
      "llama3.2:latest",
      "gpt-oss:120b-cloud",
      "gpt-oss:20b-cloud",
      "deepseek-v3.1:671b-cloud",
      "qwen3-coder:480b-cloud",
      "qwen3-vl:235b-cloud",
      "minimax-m2:cloud",
      "glm-4.6:cloud",
    ],
    baseUrl: "http://127.0.0.1:11434",
    mode: "local",
    enabled: true,
    dynamicModels: true,
  },
  {
    id: "nvidia",
    provider: "nvidia",
    model: "nvidia/llama-3.3-nemotron-super-49b-v1",
    baseUrl: "https://integrate.api.nvidia.com/v1",
    mode: "cloud",
    enabled: false,
    dynamicModels: true,
    requiresApiKey: true,
  },
  {
    id: "anthropic",
    provider: "anthropic",
    model: "claude-sonnet-4-5",
    models: ["claude-sonnet-4-5", "claude-opus-4-1", "claude-haiku-4-5"],
    mode: "cloud",
    enabled: false,
    requiresApiKey: true,
  },
  {
    id: "openai",
    provider: "openai",
    model: "gpt-5.5",
    models: [
      "gpt-5.5",
      "gpt-5.5-mini",
      "gpt-5.5-nano",
      "gpt-5.5-thinking",
      "gpt-5.2",
      "gpt-5.2-mini",
      "gpt-5.2-nano",
      "gpt-4.1",
      "o4-mini",
      "o3",
    ],
    mode: "cloud",
    enabled: false,
    requiresApiKey: true,
    dynamicModels: true,
  },
  { id: "openrouter", provider: "openrouter", model: "auto", models: ["auto"], mode: "cloud", enabled: false, requiresApiKey: true },
  {
    id: "gemini-cli",
    provider: "gemini-cli",
    model: "gemini-2.5-pro",
    models: ["gemini-2.5-pro", "gemini-2.5-flash", "gemini-2.5-flash-lite"],
    mode: "cli",
    enabled: true,
    dynamicModels: true,
  },
  {
    id: "gemini",
    provider: "gemini",
    model: "gemini-2.5-pro",
    models: ["gemini-2.5-pro", "gemini-2.5-flash", "gemini-2.5-flash-lite"],
    mode: "cloud",
    enabled: false,
    requiresApiKey: true,
  },
  { id: "grok", provider: "grok", model: "grok-4", models: ["grok-4", "grok-3"], mode: "cloud", enabled: false, requiresApiKey: true },
  { id: "custom", provider: "custom", model: "custom-endpoint", mode: "cloud", enabled: false },
];

export function listModelProviders() {
  return modelEndpoints;
}

export function getProvider(id: ModelProvider | string) {
  return modelEndpoints.find((endpoint) => endpoint.id === id || endpoint.provider === id);
}
